name: WebTransport Interop
on:
  push:
    branches:
      - webtransport-debug

jobs:
  run:
    uses: ./.github/workflows/interop.yml
    with:
      protocol: webtransport
      implementations_file: implementations_webtransport.json
      upload_dir: ${{ vars.LOG_DIR_WEBTRANSPORT }}
      upload_results: true
      run_measurements: false
    secrets: inherit
